export const ERROR_CODES = {
    ALREADY_IN_ROOM: "ALREADY_IN_ROOM",
    ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
    ROOM_FULL: "ROOM_FULL",
    INVALID_STATE: "INVALID_STATE",
    NOT_YOUR_TURN: "NOT_YOUR_TURN",
    NOT_ALLOWED_ACTOR: "NOT_ALLOWED_ACTOR",
    INVALID_QUESTION_FORMAT: "INVALID_QUESTION_FORMAT",
    INVALID_ANSWER: "INVALID_ANSWER",
    INVALID_FLAG: "INVALID_FLAG",
    ALREADY_ELIMINATED: "ALREADY_ELIMINATED",
    INVALID_TEXT: "INVALID_TEXT",
    TEXT_TOO_LONG: "TEXT_TOO_LONG",
    RATE_LIMITED: "RATE_LIMITED"
};
